/* user login */
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const RESET_USER_LOGIN = "RESET_USER_LOGIN";

/* user registration */
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
export const RESET_USER_REGISTER = "RESET_USER_REGISTER";

/* member list */
export const GET_MEMBERS = "GET_MEMBERS";
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const GET_MEMBERS_FAILURE = "GET_MEMBERS_FAILURE";

/* get member profile */
export const GET_MEMBER_PROFILE = "GET_MEMBER_PROFILE";
export const GET_MEMBER_PROFILE_SUCCESS = "GET_MEMBER_PROFILE_SUCCESS";
export const GET_MEMBER_PROFILE_FAILURE = "GET_MEMBER_PROFILE_FAILURE";
export const LOAD_EDIT_MEMBER_PROFILE = "LOAD_EDIT_MEMBER_PROFILE";
export const LOAD_EDIT_MEMBER_PROFILE_SUCCESS =
  "LOAD_EDIT_MEMBER_PROFILE_SUCCESS";
export const LOAD_EDIT_MEMBER_PROFILE_FAILURE =
  "LOAD_EDIT_MEMBER_PROFILE_FAILURE";
export const LOAD_VIEW_MEMBER_PROFILE = "LOAD_VIEW_MEMBER_PROFILE";

/* update member profile */
export const UPDATE_MEMBER_PROFILE = "UPDATE_MEMBER_PROFILE";
export const UPDATE_MEMBER_PROFILE_SUCCESS = "UPDATE_MEMBER_PROFILE_SUCCESS";
export const UPDATE_MEMBER_PROFILE_FAILURE = "UPDATE_MEMBER_PROFILE_FAILURE";

/* get my profile */
export const GET_MY_PROFILE = "GET_MY_PROFILE";
export const GET_MY_PROFILE_SUCCESS = "GET_MY_PROFILE_SUCCESS";
export const GET_MY_PROFILE_FAILURE = "GET_MY_PROFILE_FAILURE";
export const LOAD_EDIT_PROFILE = "LOAD_EDIT_PROFILE";
export const LOAD_VIEW_PROFILE = "LOAD_VIEW_PROFILE";

/* update my profile */
export const UPDATE_MY_PROFILE = "UPDATE_MY_PROFILE";
export const UPDATE_MY_PROFILE_SUCCESS = "UPDATE_MY_PROFILE_SUCCESS";
export const UPDATE_MY_PROFILE_FAILURE = "UPDATE_MY_PROFILE_FAILURE";

/* Create new event */
export const CREATE_NEW_EVENT = "CREATE_NEW_EVENT";
export const CREATE_NEW_EVENT_SUCCESSFUL = "CREATE_NEW_EVENT_SUCCESSFUL";
export const CREATE_NEW_EVENT_FAILURE = "CREATE_NEW_EVENT_FAILURE";

/* Get elemnts for details for edit event */
export const GET_EDIT_EVENT_DETAILS = "GET_EDIT_EVENT_DETAILS";
export const GET_EDIT_EVENT_DETAILS_SUCCESSFUL =
  "GET_EDIT_EVENT_DETAILS_SUCCESSFUL";
export const GET_EDIT_EVENT_DETAILS_FAILURE = "GET_EDIT_EVENT_DETAILS_FAILURE";

/* Get elemnts for details for edit event */
export const EDIT_EVENT_DETAILS = "EDIT_EVENT_DETAILS";
export const EDIT_EVENT_DETAILS_SUCCESSFUL = "EDIT_EVENT_DETAILS_SUCCESSFUL";
export const EDIT_EVENT_DETAILS_FAILURE = "EDIT_EVENT_DETAILS_FAILURE";

/* Get Public Page Stuff */
export const GET_PUBLIC_SCHEDULER = "GET_PUBLIC_SCHEDULER";
export const GET_PUBLIC_SCHEDULER_SUCCESSFUL =
  "GET_PUBLIC_SCHEDULER_SUCCESSFUL";
export const GET_PUBLIC_SCHEDULER_FAILURE = "GET_PUBLIC_SCHEDULER_FAILURE";
